spring.datasource.url=jdbc:postgresql://localhost:5432/deposit_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# for Spring Boot 3
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

